FROM registry.access.redhat.com/ubi8/ubi:8.1

MAINTAINER anyOpsOS

WORKDIR /var/www

RUN yum -y update && \
curl -sL https://rpm.nodesource.com/setup_14.x | bash - && \
yum -y install nodejs && \
npm install -g yarn nodemon

ENV NODE_ENV production
ENV AOO_ANYOPSOS_TYPE filesystem

EXPOSE 443

ENTRYPOINT ["nodemon", "-e", "js", "--experimental-loader", "./https-loader.js", "--experimental-specifier-resolution=node", "index.js"]
