FROM centos:8

MAINTAINER anyOpsOS

WORKDIR /var/www

ENV PATH="/var/www/node_modules/.bin:${PATH}"

RUN yum -y update && \
yum -y install nodejs git python3 make gcc gcc-c++ openssh-server && \
npm install -g yarn

ADD assets/start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 22

ENTRYPOINT ["/start.sh"]
