FROM registry.access.redhat.com/ubi8/ubi:8.1

MAINTAINER anyOpsOS

WORKDIR /var/www

RUN yum -y update && \
curl -sL https://rpm.nodesource.com/setup_13.x | bash - && \
yum -y install nodejs && \
npm install -g yarn nodemon

ENV NODE_ENV production

EXPOSE 443

ENTRYPOINT ["nodemon", "--experimental-modules", "--experimental-loader", "./https-loader.js", "--experimental-specifier-resolution=node", "index.js"]
